#!/bin/bash
# Auto-generated by NetSec (Fixer)
# Purpose: Secure UFW firewall settings

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

set -e

echo "[-] Resetting UFW..."
ufw --force reset

echo "[-] Setting default policies..."
ufw default deny incoming
ufw default allow outgoing

echo "[-] Allowing Local LAN (192.168.0.0/24)..."
ufw allow from 192.168.0.0/24

echo "[-] Allowing Tailscale (tailscale0 & 100.64.0.0/10)..."
ufw allow in on tailscale0
ufw allow from 100.64.0.0/10

echo "[-] Limiting SSH..."
ufw limit ssh

echo "[-] Enabling UFW..."
ufw --force enable

echo "[+] Done. Status:"
ufw status numbered
