#!/bin/bash

# Research Refresh Cron Job
# Runs daily to check for stale research and notify Morpheus
# Usage: Add to crontab or run manually

set -euo pipefail

WORKSPACE="$HOME/.openclaw/workspace"
LOG_FILE="$WORKSPACE/logs/research-refresh-cron.log"
CHECKER_SCRIPT="$WORKSPACE/scripts/check-research-refresh.py"

# Ensure log directory exists
mkdir -p "$WORKSPACE/logs"

# Log with timestamp
log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log "=== Research Refresh Check (Cron) ==="

# Run checker in JSON mode
RESULT=$(python3 "$CHECKER_SCRIPT" --json 2>&1)
EXIT_CODE=$?

# Parse result to count overdue entries
OVERDUE_COUNT=$(echo "$RESULT" | jq '[.[] | select(.status_freshness == "overdue")] | length' 2>/dev/null || echo "0")
DUE_SOON_COUNT=$(echo "$RESULT" | jq '[.[] | select(.status_freshness == "due_soon")] | length' 2>/dev/null || echo "0")

log "Overdue: $OVERDUE_COUNT | Due Soon: $DUE_SOON_COUNT"

# If research is stale, create alert file for Morpheus
if [ "$OVERDUE_COUNT" -gt 0 ]; then
  ALERT_FILE="$WORKSPACE/.research-refresh-alert"
  
  # Extract overdue entries
  OVERDUE_ENTRIES=$(echo "$RESULT" | jq -r '[.[] | select(.status_freshness == "overdue")] | .[] | "- \(.title) (\(.file)): \(.days_until_refresh | tonumber | . * -1) days overdue"' 2>/dev/null)
  
  # Write alert file
  cat > "$ALERT_FILE" <<EOF
# Research Refresh Alert

**Date:** $(date +'%Y-%m-%d %H:%M:%S')  
**Status:** $OVERDUE_COUNT research file(s) need refresh

## Overdue Research

$OVERDUE_ENTRIES

## Action Required

1. Review overdue topics
2. Spawn Scout to update stale research
3. Update RESEARCH_INDEX.md with new refresh dates
4. Run: \`python3 scripts/check-research-refresh.py\` to verify

## Auto-Update (Future)

When ready, implement auto-update:
- Parse RESEARCH_INDEX.md for overdue entries
- Spawn Scout with original research query
- Update research files automatically
- Update RESEARCH_INDEX.md dates

---
Generated by: scripts/research-refresh-cron.sh
EOF

  log "⚠️  Alert created: $ALERT_FILE"
  log "Morpheus will see this on next heartbeat or session start"
  
else
  # Remove alert file if exists (all research is fresh)
  ALERT_FILE="$WORKSPACE/.research-refresh-alert"
  if [ -f "$ALERT_FILE" ]; then
    rm "$ALERT_FILE"
    log "✅ Alert cleared (all research is fresh)"
  else
    log "✅ All research is fresh (no action needed)"
  fi
fi

log "=== Check Complete ==="
exit 0
